### ISSUE TITLE
v0.0.8 still emits console.logs 

### ISSUE THREAD

**Issue by camhammel** [akhmadshin/next-rich-view-transitions#1]
I can see that in the [latest commit for v.0.0.8](https://github.com/akhmadshin/next-rich-view-transitions/commit/979789a7eb429999bc55175a31b47d56f7402134) the console logs were removed, but even with this version installed (I only started using this library today), it looks like they're still being emitted in the application:

![image](https://github.com/user-attachments/assets/c73bbcce-0e1d-4430-ba8a-8a7be78e4a70)

my version in `package.json`: 
![image](https://github.com/user-attachments/assets/c1e709ce-1bd5-4f40-af58-b1d3d19cfe2b)

**Comment by akhmadshin** [comment]
Thanks! Gonna fix it today
